language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    # - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh

install:
  - sudo luarocks install luacov-coveralls --server=http://rocks.moonscript.org/dev
  - sudo luarocks install lunitx --server=https://rocks.moonscript.org/manifests/moteus
  - sudo luarocks install https://raw.github.com/moteus/luacrypto/master/rockspecs/luacrypto-git-1.rockspec
  - sudo luarocks install luasocket
  # Test lpeg 10 with Lua 5.1 and last with  Lua 5.2
  - if [ $LUA_VER = "5.1" ]; then 
      sudo luarocks install lpeg 0.10;
    else
      sudo luarocks install lpeg;
    fi
  - sudo luarocks install lua-iconv
  - sudo luarocks make rockspecs/pop3-scm-0.rockspec

script:
  - cd test
  - lunit.sh -i lua$LUA_SFX test-message.lua

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
