language: c

sudo: false

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

before_install:
  - export CC=gcc
  - pip install --user cpp-coveralls
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

install:
  - luarocks show luasocket || luarocks install luasocket
  - luarocks show lua-iconv || luarocks install lua-iconv
  - luarocks show luacrypto || luarocks install luacrypto
  - luarocks show lpeg      || luarocks install lpeg
  - luarocks make rockspecs/pop3-scm-0.rockspec

before_script:
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls
  - luarocks show lunitx           || luarocks install lunitx

script:
  - cd test
  - lunit.sh -i lua$LUA_SFX test-message.lua

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
